Development:

stripe_secret_key: 'sk_test_51KEygrHnE113267qsOz3qIS3XbPdzq4R7syorb6u9rJqQb0IZVd5quKEIB2vyACYGY5ttVwCPeeimGEf3Epv0HMW00vy517XtI'
stripe_publishable_key: 'pk_test_51KEygrHnE113267qJNXGOA0WUS9gvOmeiaIdwCOzc51he0QhZxZmIURneIYpHD01mXlkBiFZzw1ayTiEYNuzKyVk00lrMoEnuQ'

production:

stripe_secret_key: 'sk_test_51KEygrHnE113267qsOz3qIS3XbPdzq4R7syorb6u9rJqQb0IZVd5quKEIB2vyACYGY5ttVwCPeeimGEf3Epv0HMW00vy517XtI'
stripe_publishable_key: 'pk_test_51KEygrHnE113267qJNXGOA0WUS9gvOmeiaIdwCOzc51he0QhZxZmIURneIYpHD01mXlkBiFZzw1ayTiEYNuzKyVk00lrMoEnuQ'
